import {
  ICE_REFLECTION_ANNULUS_STRENGTH,
  ICE_REFLECTION_BLEND,
  ICE_REFLECTION_FISHEYE_PEAK,
  ICE_REFLECTION_FISHEYE_STRENGTH,
  ICE_REFLECTION_OPACITY,
  ICE_REFLECTION_POOL_HALF_CELL,
  ICE_REFLECTION_POOL_SPRITE_FRAC,
} from "../combat/IceBlockFx";
import {
  WARP_ORB_REFLECTION_ANNULUS_STRENGTH,
  WARP_ORB_REFLECTION_BLEND,
  WARP_ORB_REFLECTION_FISHEYE_PEAK,
  WARP_ORB_REFLECTION_FISHEYE_STRENGTH,
  WARP_ORB_REFLECTION_OPACITY,
  WARP_ORB_REFLECTION_POOL_HALF_CELL,
  WARP_ORB_REFLECTION_POOL_SPRITE_FRAC,
} from "../combat/WarpOrbFx";

/** Parameters for {@link LiveReflectionEffect}. */
export type LiveReflectionStyle = {
  opacity: number;
  blendMode: string;
  poolHalfCellTiles: number;
  poolSpriteFrac: number;
  fisheyePeak: number;
  fisheyeStrength: number;
  annulusStrength: number;
};

export const ICE_BLOCK_REFLECTION_STYLE: LiveReflectionStyle = {
  opacity: ICE_REFLECTION_OPACITY,
  blendMode: ICE_REFLECTION_BLEND,
  poolHalfCellTiles: ICE_REFLECTION_POOL_HALF_CELL,
  poolSpriteFrac: ICE_REFLECTION_POOL_SPRITE_FRAC,
  fisheyePeak: ICE_REFLECTION_FISHEYE_PEAK,
  fisheyeStrength: ICE_REFLECTION_FISHEYE_STRENGTH,
  annulusStrength: ICE_REFLECTION_ANNULUS_STRENGTH,
};

export const WARP_ORB_REFLECTION_STYLE: LiveReflectionStyle = {
  opacity: WARP_ORB_REFLECTION_OPACITY,
  blendMode: WARP_ORB_REFLECTION_BLEND,
  poolHalfCellTiles: WARP_ORB_REFLECTION_POOL_HALF_CELL,
  poolSpriteFrac: WARP_ORB_REFLECTION_POOL_SPRITE_FRAC,
  fisheyePeak: WARP_ORB_REFLECTION_FISHEYE_PEAK,
  fisheyeStrength: WARP_ORB_REFLECTION_FISHEYE_STRENGTH,
  annulusStrength: WARP_ORB_REFLECTION_ANNULUS_STRENGTH,
};
