import { TILE_SIZE } from "../../specs";

/** Authoritative whip physics + wiggle-phase tuning (Java WhipTuningValues). */
export const WhipTuningValues = {
  TILE_PX: TILE_SIZE,

  CRACK_RADIUS_TILES: 3.0,
  CRACK_RADIUS_PER_STACK_TILES: 1.0,
  WIGGLE_RADIUS_TILES: 1.0,

  WIGGLE_DAMAGE_MULT: 0.35,
  WIGGLE_HIT_COOLDOWN_SEC: 0.14,
  WIGGLE_RECOVER_EARLY_MULT: 1.0,
  WIGGLE_RETRACT_SPEED_PX_PER_SEC: 48.0,
  WIGGLE_MOVE_SPEED_PX_PER_SEC: 210.0,
  WIGGLE_TIP_TRACK_SPEED_PX_PER_SEC: 340.0,
  WIGGLE_INPUT_UP_MULT: 1.85,
  WIGGLE_INPUT_DOWN_MULT: 0.38,
  WIGGLE_INPUT_HORIZONTAL_MULT: 1.0,
  WIGGLE_HEAD_ANGLE_BLEND: 0.16,
  WIGGLE_CLAMP_ALL_POINTS: true,

  WIGGLE_STRETCH_LIMIT_MULT: 1.06,
  WIGGLE_SNAP_LIMIT_MULT: 1.14,
  WIGGLE_TIP_DAMPING: 0.9,
  WIGGLE_CHAIN_COLLIDE_PUSH: 6.0,
  WIGGLE_LINK_GRAVITY_SCALE: 0.48,
  WIGGLE_TIP_GRAVITY_SCALE: 0.52,

  CRACK_STRETCH_LIMIT_MULT: 1.01,
  CRACK_SNAP_LIMIT_MULT: 1.04,
  CRACK_STEER_ACCEL: 1500.0,
  CRACK_IMPULSE: 42.0,
  CRACK_STEER_SCALE: 0.35,
  CRACK_TIP_DAMPING: 0.96,
  CRACK_CHAIN_COLLIDE_PUSH: 3.0,
  CRACK_LINK_GRAVITY_SCALE: 0.08,
  CRACK_TIP_GRAVITY_SCALE: 0.12,
  CRACK_STEER_STRENGTH: 0.82,
  CRACK_HEAD_ANGLE_BLEND: 0.45,
  CRACK_ENFORCE_TIP_BLEND: 0.36,
  CRACK_ENFORCE_STRAIGHTEN_BLEND: 0.2,
  ENFORCE_INTERIOR_VERLET_BLEND: 0.35,

  crackRadiusPx(whipStacks: number): number {
    return (
      (this.CRACK_RADIUS_TILES + Math.max(0, whipStacks) * this.CRACK_RADIUS_PER_STACK_TILES) *
      this.TILE_PX
    );
  },

  wiggleRadiusPx(): number {
    return this.WIGGLE_RADIUS_TILES * this.TILE_PX;
  },
} as const;
