/**
 * Authoritative hitbox geometry in texture-local space (Java `game.config.HitboxValues`).
 * Regenerated by desktop HitboxEditor — do not invent polygons.
 *
 * Roles: COLLISION / PLAYER / ENEMY_* — solids / world.
 * *_HIT / offensive strips — deal damage. *_HURT / PLAYER_HURT — receive damage.
 * Pickups: pickup() = collection (Hit), pickupPhysics() = tile collision.
 */

import { PickupKind } from "../world/BreakableLootRoll";

export const PLAYER_STAND_HITBOX_H = 18;
export const PLAYER_WIDTH = 10;
export const PLAYER_PIVOT_LOCAL_X = PLAYER_WIDTH * 0.5;

/** Stand collision polygon (0,0)-(10,0)-(10,18)-(0,18). */
export const PLAYER_STAND_LOCAL = [0, 0, 10, 0, 10, 18, 0, 18];

/** Player damage / vulnerability hull. */
export const PLAYER_HURT_LOCAL = [
  3, -5, 7, -5, 9, -1, 7, 0, 10, 7, 8, 18, 2, 18, 0, 7, 3, 0, 1, -1,
];
export const PLAYER_HURT_PIVOT_X = 5;

/** Reference height for PLAYER_JUMP local Y scale (editor / vernan jump.png). */
export const PLAYER_JUMP_STAND_HITBOX_H = 18;

/** Air collision when airborne (not crouch-jump, not climbing). */
export const PLAYER_JUMP_LOCAL = [0, 0, 10, 0, 10, 5, 4, 11, 0, 13];
/** AABB height of jump polygon (debug / HUD). */
export const PLAYER_JUMP_HITBOX_H = 13;
export const PLAYER_JUMP_PIVOT_X = 5;
/** Local Y of jump lead foot (right tip) and trail foot (left tip). */
export const PLAYER_JUMP_LEAD_FOOT_LOCAL_X = 10;
export const PLAYER_JUMP_LEAD_FOOT_LOCAL_Y = 5;
export const PLAYER_JUMP_TRAIL_FOOT_LOCAL_X = 0;
export const PLAYER_JUMP_TRAIL_FOOT_LOCAL_Y = 13;
/** HitboxEditor only: jump strip feet line in local space (not used by the game). */
export const PLAYER_JUMP_EDITOR_FEET_LOCAL_Y = 18;

const PICKUP_HEART = [
  5, 2, 11, 2, 13, 5, 14, 7, 14, 11, 11, 15, 9, 15, 6, 13, 4, 11, 3, 8, 3, 5,
];
const PICKUP_KEY = [11, 3, 12, 4, 12, 7, 9, 13, 5, 13, 4, 7, 4, 4, 5, 3];
const PICKUP_COIN = [0, 2, 2, 0, 6, 0, 8, 2, 8, 6, 6, 8, 2, 8, 0, 6];

export function pickup(kind: PickupKind): number[] {
  switch (kind) {
    case PickupKind.HEART:
      return PICKUP_HEART;
    case PickupKind.KEY:
      return PICKUP_KEY;
    case PickupKind.COIN_1:
    case PickupKind.COIN_5:
    case PickupKind.COIN_10:
      return PICKUP_COIN;
  }
}

export function pickupPivotX(kind: PickupKind): number {
  switch (kind) {
    case PickupKind.HEART:
      return 8;
    case PickupKind.KEY:
      return 8;
    case PickupKind.COIN_1:
    case PickupKind.COIN_5:
    case PickupKind.COIN_10:
      return 4;
  }
}

const PICKUP_HEART_PHYS = [
  7, 4, 10, 4, 12, 5, 13, 6, 13, 11, 12, 13, 11, 14, 9, 14, 7, 13, 5, 11, 4, 8, 5, 6,
];
const PICKUP_KEY_PHYS = [
  11, 3, 12, 4, 12, 7, 11, 8, 9, 8, 9, 13, 5, 13, 5, 10, 7, 10, 7, 8, 5, 8, 4, 7, 4, 4, 5, 3,
];
const PICKUP_COIN_PHYS = [2, 2, 3, 1, 5, 1, 6, 2, 6, 6, 5, 7, 3, 7, 2, 6];

export const PICKUP_HEART_PHYS_PIVOT_X = 0;
export const PICKUP_KEY_PHYS_PIVOT_X = 0;
export const PICKUP_COIN_PHYS_PIVOT_X = 0;

export function pickupPhysics(kind: PickupKind): number[] {
  switch (kind) {
    case PickupKind.HEART:
      return PICKUP_HEART_PHYS;
    case PickupKind.KEY:
      return PICKUP_KEY_PHYS;
    case PickupKind.COIN_1:
    case PickupKind.COIN_5:
    case PickupKind.COIN_10:
      return PICKUP_COIN_PHYS;
  }
}

export function pickupPhysicsPivotX(kind: PickupKind): number {
  switch (kind) {
    case PickupKind.HEART:
      return PICKUP_HEART_PHYS_PIVOT_X;
    case PickupKind.KEY:
      return PICKUP_KEY_PHYS_PIVOT_X;
    case PickupKind.COIN_1:
    case PickupKind.COIN_5:
    case PickupKind.COIN_10:
      return PICKUP_COIN_PHYS_PIVOT_X;
  }
}

export const ENEMY_CRAWLER_LOCAL = [-1, 0, 9, 0, 9, 12, -1, 12];
export const ENEMY_CRAWLER_PIVOT_X = 4;

/** Air collision while hop-airborne — raised lead foot (facing +X), trail at stand bottom. */
export const ENEMY_CRAWLER_HOP_LOCAL = [-1, 0, 9, 0, 9, 5, 3, 10, -1, 12];
export const ENEMY_CRAWLER_HOP_PIVOT_X = 4;

export const ENEMY_CRAWLER_HIT_LOCAL = [-1, 0, 9, 0, 9, 12, -1, 12];
export const ENEMY_CRAWLER_HIT_PIVOT_X = 4;

export const ENEMY_CRAWLER_HURT_LOCAL = [
  -3, -3, 1, -4, 7, -4, 11, -3, 12, 1, 12, 9, 9, 12, -1, 12, -4, 9, -4, 1,
];
export const ENEMY_CRAWLER_HURT_PIVOT_X = 4;

export const ENEMY_PENISMAN_LOCAL = [-2, 1, 10, 1, 10, 13, -2, 13];
export const ENEMY_PENISMAN_PIVOT_X = 4;

export const ENEMY_PENISMAN_HIT_LOCAL = [1, 2, 7, 2, 9, 13, -1, 13];
export const ENEMY_PENISMAN_HIT_PIVOT_X = 4;

export const ENEMY_PENISMAN_HURT_LOCAL = [-3, -3, 11, -3, 11, 13, -3, 13];
export const ENEMY_PENISMAN_HURT_PIVOT_X = 4;

export const ENEMY_MOUSE_LOCAL = [-2, 5, 10, 5, 10, 13, -2, 13];
export const ENEMY_MOUSE_PIVOT_X = 4;

export const ENEMY_MOUSE_HIT_LOCAL = [0, 7, 8, 7, 9, 13, -1, 13];
export const ENEMY_MOUSE_HIT_PIVOT_X = 4;

export const ENEMY_MOUSE_HURT_LOCAL = [-4, 2, 12, 2, 12, 13, -4, 13];
export const ENEMY_MOUSE_HURT_PIVOT_X = 4;

/** Golden roach — walk (8×8 art): collision + hurt only. */
export const ENEMY_GOLDEN_ROACH_WALK_LOCAL = [1, 1, 7, 1, 7, 7, 1, 7];
export const ENEMY_GOLDEN_ROACH_WALK_PIVOT_X = 4;

export const ENEMY_GOLDEN_ROACH_WALK_HURT_LOCAL = [0, 0, 8, 0, 8, 8, 0, 8];
export const ENEMY_GOLDEN_ROACH_WALK_HURT_PIVOT_X = 4;

/** Golden roach — fly (16×8 art): collision + hurt + contact hit. */
export const ENEMY_GOLDEN_ROACH_FLY_LOCAL = [5, 5, 11, 5, 11, 11, 5, 11];
export const ENEMY_GOLDEN_ROACH_FLY_PIVOT_X = 8;

export const ENEMY_GOLDEN_ROACH_FLY_HURT_LOCAL = [1, 3, 10, 3, 12, 4, 13, 6, 13, 14, 7, 14, 1, 8];
export const ENEMY_GOLDEN_ROACH_FLY_HURT_PIVOT_X = 8;

export const ENEMY_GOLDEN_ROACH_FLY_HIT_LOCAL = [4, 4, 11, 5, 12, 12, 5, 11];
export const ENEMY_GOLDEN_ROACH_FLY_HIT_PIVOT_X = 8;

export const ENEMY_JACK_BLUE_LOCAL = [-2, -14, 10, -14, 10, 13, -2, 13];
export const ENEMY_JACK_BLUE_PIVOT_X = 4;

export const ENEMY_JACK_BLUE_HIT_LOCAL = [2, -15, 10, -15, 10, 13, 2, 13];
export const ENEMY_JACK_BLUE_HIT_PIVOT_X = 4;

export const ENEMY_JACK_BLUE_HURT_LOCAL = [
  0, -19, 15, -19, 15, -9, 10, -6, 15, -2, 15, 6, 10, 13, -4, 13, -4, -6, 0, -6,
];
export const ENEMY_JACK_BLUE_HURT_PIVOT_X = 4;

/** Jack Blue held shield — body-local feet-on-poly space. */
export const ENEMY_JACK_BLUE_SHIELD_LOCAL = [-7, -18, -1, -18, -1, -4, -7, -4];
export const ENEMY_JACK_BLUE_SHIELD_PIVOT_X = 4;

/** Multilimber body tile physics. */
export const ENEMY_MULTILIMBER_LOCAL = [-6, -17, 14, -17, 14, 5, -6, 5];
export const ENEMY_MULTILIMBER_PIVOT_X = 4;
export const ENEMY_MULTILIMBER_EDITOR_FEET_LOCAL_Y = 7;

export const ENEMY_MULTILIMBER_HIT_LOCAL = [
  -1, -18, 10, -18, 13, -15, 13, -2, 10, 1, -1, 1, -4, -2, -4, -15,
];
export const ENEMY_MULTILIMBER_HIT_PIVOT_X = 4;

export const ENEMY_MULTILIMBER_HURT_LOCAL = [-11, -24, 19, -24, 19, 6, -11, 6];
export const ENEMY_MULTILIMBER_HURT_PIVOT_X = 4;

export const ENEMY_MULTILIMBER_EYE_HURT_LOCAL = [-5, -11, 0, -11, 0, -6, -5, -6];
export const ENEMY_MULTILIMBER_EYE_HURT_PIVOT_X = 4;

export const ENEMY_MULTILIMBER_HEAD_HURT_LOCAL = [
  -7, -17, -4, -20, 0, -20, 2, -19, 5, -16, 7, -12, 7, -6, 5, -2, 2, 1, -2, 1, -5, -2, -7, -6,
];
export const ENEMY_MULTILIMBER_HEAD_HURT_PIVOT_X = 4;

export const ENEMY_ROLLING_HEAD_LOCAL = [-3, -2, 11, -2, 11, 12, -3, 12];
export const ENEMY_ROLLING_HEAD_PIVOT_X = 4;
export const ENEMY_ROLLING_HEAD_EDITOR_FEET_LOCAL_Y = 13;

export const ENEMY_ROLLING_HEAD_HIT_LOCAL = [0, 0, 8, 0, 8, 10, 0, 10];
export const ENEMY_ROLLING_HEAD_HIT_PIVOT_X = 4;

export const ENEMY_ROLLING_HEAD_HURT_LOCAL = [-4, -3, 12, -3, 12, 13, -4, 13];
export const ENEMY_ROLLING_HEAD_HURT_PIVOT_X = 4;

export const PROJECTILE_JACK_BONE_LOCAL = [4, 4, 12, 4, 12, 12, 4, 12];
export const PROJECTILE_JACK_BONE_PIVOT_X = 8;

export const PROJECTILE_JACK_BONE_HIT_LOCAL = [6, 5, 10, 5, 10, 11, 6, 11];
export const PROJECTILE_JACK_BONE_HIT_PIVOT_X = 8;

export const PROJECTILE_PENIS_BULLET_LOCAL = [0, 4, 4, 4, 4, 8, 0, 8];
export const PROJECTILE_PENIS_BULLET_PIVOT_X = 3;

export const PROJECTILE_PENIS_BULLET_HIT_LOCAL = [-1, 3, 5, 3, 5, 9, -1, 9];
export const PROJECTILE_PENIS_BULLET_HIT_PIVOT_X = 3;

export const SHIELD_STAND_LOCAL = [23, 8, 28, 8, 28, 23, 21, 23];
export const SHIELD_STAND_PIVOT_X = 16;

export const SHIELD_CROUCH_LOCAL = [23, 16, 28, 16, 28, 31, 21, 31];
export const SHIELD_CROUCH_PIVOT_X = 16;

export const BRICK_CHUNK_DEBRIS_LOCAL = [1, 1, 6, 1, 5, 5, 1, 7];
export const BRICK_CHUNK_DEBRIS_PIVOT_X = 0;

/** Sword swing hitbox active during attackPhase == 2. */
export const SWORD_ATTACK_ACTIVE_LOCAL = [
  28, 5, 35, 8, 40, 16, 42, 28, 31, 28, 25, 27, 16, 20, 11, 12, 14, 5,
];
export const SWORD_ATTACK_ACTIVE_PIVOT_X = 16;

/** Shield arm hitbox active during attackPhase == 1 when SHIELD is held. */
export const SHIELD_ATTACK_WINDUP_LOCAL = [14, 11, 25, 8, 27, 14, 26, 22, 21, 23, 16, 19];
export const SHIELD_ATTACK_WINDUP_PIVOT_X = 16;

/** Crouch-attack sword active frame. */
export const SWORD_CROUCH_ATTACK_ACTIVE_LOCAL = [
  28, 16, 36, 20, 41, 24, 41, 32, 28, 32, 26, 26, 21, 22, 11, 22, 11, 17, 16, 15, 23, 15,
];
export const SWORD_CROUCH_ATTACK_ACTIVE_PIVOT_X = 16;

/** disc01 slide kick — low leg strip. */
export const SLIDE_KICK_ACTIVE_LOCAL = [
  21, 21, 31, 27, 31, 34, 15, 34, 13, 32, 2, 32, 5, 18, 11, 13, 17, 13,
];
export const SLIDE_KICK_ACTIVE_PIVOT_X = 16;

export const HEADBAND_CROUCH_ATTACK1_ACTIVE_LOCAL = [
  21, 22, 34, 24, 34, 33, 27, 33, 17, 30, 11, 26, 11, 20, 15, 18,
];
export const HEADBAND_CROUCH_ATTACK1_ACTIVE_PIVOT_X = 16;

export const HEADBAND_UP_ATTACK0_ACTIVE_LOCAL = [
  26, -1, 35, -1, 35, 11, 34, 24, 31, 29, 23, 27, 25, 21, 26, 11,
];
export const HEADBAND_UP_ATTACK0_ACTIVE_PIVOT_X = 16;

export const HEADBAND_SIDE_ATTACK0_SETUP_LOCAL = [
  21, 12, 26, 17, 26, 27, 22, 33, 11, 33, 6, 27, 6, 17, 11, 12,
];
export const HEADBAND_SIDE_ATTACK0_SETUP_PIVOT_X = 16;

export const HEADBAND_SIDE_ATTACK0_ACTIVE_A_LOCAL = [
  27, 12, 32, 13, 32, 28, 27, 29, 17, 33, 11, 33, 11, 17, 16, 14,
];
export const HEADBAND_SIDE_ATTACK0_ACTIVE_A_PIVOT_X = 16;

export const HEADBAND_SIDE_ATTACK0_ACTIVE_B_LOCAL = [
  14, 14, 21, 17, 20, 33, 13, 33, 3, 28, 0, 26, 0, 14, 4, 13,
];
export const HEADBAND_SIDE_ATTACK0_ACTIVE_B_PIVOT_X = 16;

// Local X −2 vs prior authoring: matches attack1 strip art (hit frame 2 shifted left 2px).
export const HEAVY_ATTACK1_SWORD_ACTIVE_LOCAL = [
  32, 14, 41, 18, 46, 28, 48, 36, 48, 48, 43, 48, 36, 45, 23, 35, 9, 32, 5, 32, 5, 26, 8, 20, 11, 17, 15, 15, 20, 14,
];
export const HEAVY_ATTACK1_SWORD_ACTIVE_PIVOT_X = 16;

export const HEAVY_ATTACK1_FLINT_ACTIVE_LOCAL = [
  29, 28, 35, 31, 41, 37, 42, 40, 42, 44, 33, 44, 27, 43, 19, 38, 12, 34, 4, 32, 4, 28, 14, 26, 21, 26,
];
export const HEAVY_ATTACK1_FLINT_ACTIVE_PIVOT_X = 16;

export const HEAVY_ATTACK1_GEM_ACTIVE_LOCAL = [
  36, 16, 40, 20, 43, 25, 46, 34, 46, 44, 43, 46, 35, 46, 32, 45, 24, 38, 17, 34, 8, 33, 3, 33, 3, 24, 6, 18, 11, 14, 18, 12, 28, 12,
];
export const HEAVY_ATTACK1_GEM_ACTIVE_PIVOT_X = 16;

export const HEAVY_ATTACK1_STICK_ACTIVE_LOCAL = [
  44, 21, 56, 33, 56, 47, 45, 47, 1, 38, 1, 33, 5, 27, 10, 21, 17, 17, 20, 16, 32, 16,
];
export const HEAVY_ATTACK1_STICK_ACTIVE_PIVOT_X = 16;

export const SHIELD_CROUCH_ATTACK_WINDUP_LOCAL = [17, 17, 27, 17, 27, 27, 25, 30, 20, 30, 17, 27];
export const SHIELD_CROUCH_ATTACK_WINDUP_PIVOT_X = 16;

export const SWORD_FLINT_ATTACK_ACTIVE_LOCAL = [
  12, 18, 20, 20, 33, 22, 36, 25, 36, 31, 24, 31, 12, 27, 1, 18, 2, 14, 8, 17,
];
export const SWORD_FLINT_ATTACK_ACTIVE_PIVOT_X = 16;

export const SWORD_FLINT_CROUCH_ATTACK_ACTIVE_LOCAL = [
  26, 22, 33, 22, 36, 25, 36, 32, 23, 32, 18, 30, 14, 27, 10, 22, 10, 18, 14, 18, 18, 21,
];
export const SWORD_FLINT_CROUCH_ATTACK_ACTIVE_PIVOT_X = 16;

export const FLINT_FIRE_LOCAL = [5, 7, 11, 7, 11, 15, 5, 15];
export const FLINT_FIRE_PIVOT_X = 16;

export const FLINT_FIRE_HIT_LOCAL = [5, 4, 11, 4, 14, 10, 13, 16, 3, 16, 2, 10];
export const FLINT_FIRE_HIT_PIVOT_X = 16;

export const PROJECTILE_FRISBEE_LOCAL = [4, 6, 12, 6, 12, 11, 4, 11];
export const PROJECTILE_FRISBEE_PIVOT_X = 8;

export const PROJECTILE_FRISBEE_HIT_LOCAL = [1, 4, 4, 1, 12, 1, 15, 4, 15, 12, 12, 15, 4, 15, 1, 12];
export const PROJECTILE_FRISBEE_HIT_PIVOT_X = 8;

export const PROJECTILE_CARRY_FRUIT_LOCAL = [2, 17, 14, 17, 14, 27, 2, 27];
export const PROJECTILE_CARRY_FRUIT_PIVOT_X = 8;

export const PROJECTILE_CARRY_FRUIT_HIT_LOCAL = [1, 17, 15, 17, 15, 31, 1, 31];
export const PROJECTILE_CARRY_FRUIT_HIT_PIVOT_X = 8;

export const PROJECTILE_CARRY_BLOCK_LOCAL = [0, 0, 16, 0, 16, 16, 0, 16];
export const PROJECTILE_CARRY_BLOCK_PIVOT_X = 8;

export const PROJECTILE_CARRY_BLOCK_HIT_LOCAL = [0, 0, 16, 0, 16, 16, 0, 16];
export const PROJECTILE_CARRY_BLOCK_HIT_PIVOT_X = 8;

export const PROJECTILE_LEMON_SHOT_LOCAL = [6, 6, 10, 6, 10, 10, 6, 10];
export const PROJECTILE_LEMON_SHOT_PIVOT_X = 4;

export const PROJECTILE_LEMON_SHOT_HIT_LOCAL = [5, 5, 11, 5, 13, 7, 13, 9, 11, 11, 5, 11, 3, 9, 3, 7];
export const PROJECTILE_LEMON_SHOT_HIT_PIVOT_X = 4;

export const PROJECTILE_WARP_ORB_LOCAL = [3, 3, 13, 3, 13, 13, 3, 13];
export const PROJECTILE_WARP_ORB_PIVOT_X = 8;

export const PROJECTILE_WARP_ORB_HIT_LOCAL = [2, 4, 5, 2, 11, 2, 14, 4, 14, 12, 11, 14, 5, 14, 2, 12];
export const PROJECTILE_WARP_ORB_HIT_PIVOT_X = 8;

export const SWORD_GEM_ATTACK_ACTIVE_LOCAL = [
  28, 5, 35, 8, 41, 16, 42, 20, 42, 26, 41, 28, 38, 29, 33, 29, 28, 28, 21, 24, 15, 17, 12, 10, 12, 5,
];
export const SWORD_GEM_ATTACK_ACTIVE_PIVOT_X = 16;

export const SWORD_GEM_CROUCH_ATTACK_ACTIVE_LOCAL = [
  27, 16, 32, 18, 38, 21, 41, 24, 41, 32, 27, 32, 26, 26, 21, 23, 11, 22, 11, 17, 14, 15, 23, 15,
];
export const SWORD_GEM_CROUCH_ATTACK_ACTIVE_PIVOT_X = 16;

export const SWORD_STICK_ATTACK_ACTIVE_LOCAL = [40, 23, 64, 23, 64, 31, 40, 31];
export const SWORD_STICK_ATTACK_ACTIVE_PIVOT_X = 40;

export const SWORD_STICK_CROUCH_ATTACK_ACTIVE_LOCAL = [40, 24, 64, 24, 64, 33, 40, 33];
export const SWORD_STICK_CROUCH_ATTACK_ACTIVE_PIVOT_X = 40;

export const SMOKE_LOCAL = [4, 2, 12, 2, 13, 3, 14, 8, 13, 13, 12, 14, 4, 14, 3, 13, 2, 8, 3, 3];
export const SMOKE_PIVOT_X = 8;

export const SMOKE_HIT_LOCAL = [4, 3, 12, 3, 14, 8, 14, 9, 12, 14, 4, 14, 2, 9, 2, 8];
export const SMOKE_HIT_PIVOT_X = 8;

/** Knockback / DI (Java Player). */
export const HURT_KNOCKBACK_X = 74;
export const HURT_KNOCKBACK_Y = -98;
export const HURT_DI_MAX_FRAC = 0.1;
export const HURT_DI_COLLISION_PROBE_PX = 2;
export const HURT_TINT_SECONDS = 0.35;
